---
deployment:
  tasks:
    - export DEPLOYPATH=/home/example/public_html/
    - /bin/cp -R assets $DEPLOYPATH
    - /bin/cp -R admin $DEPLOYPATH
    - /bin/cp -R theme $DEPLOYPATH
    - /bin/cp -R uploads $DEPLOYPATH
    - /bin/cp *.php $DEPLOYPATH
    - /bin/cp .htaccess $DEPLOYPATH
