---
deployment:
  tasks:
    - export DEPLOYPATH=/home/edisocie/public_html/
    - /bin/rm -rf $DEPLOYPATH/*
    - /bin/cp -R * $DEPLOYPATH
    - /bin/cp .htaccess $DEPLOYPATH 2>/dev/null || true
    - /bin/cp .cpanel.yml $DEPLOYPATH 2>/dev/null || true
