---
deployment:
  tasks:
    - export DEPLOYPATH=/home/edisocie/public_html/
    - /bin/mkdir -p $DEPLOYPATH/uploads
    - /usr/bin/rsync -av --exclude='uploads' --exclude='.git' --exclude='.cpanel.yml' --delete ./ $DEPLOYPATH/
    - /bin/cp .htaccess $DEPLOYPATH 2>/dev/null || true
